### ISSUE TITLE
Option to allow configuring the shortcut keys

### ISSUE THREAD

**Issue by Curly-Mo** [vmavromatis/Lemmy-keyboard-navigation#15]
I suppose the keys can be edited relatively easily in the userscript. But would be really nice if the Chrome Extension had an option to configure the shortcut keys for each action.

**Comment by vmavromatis** [comment]
I prefer to have the config window done via JS so that userscript users don't lose this feature. WDYT?

https://stackoverflow.com/questions/14594346/create-a-config-or-options-page-for-a-greasemonkey-script

**Comment by Curly-Mo** [comment]
That would be great!
In the meantime, I ended up just switching to the userscript for now and editing it to use my preferred key bindings.
