### ISSUE TITLE
Feature request: hjkl navigation

### ISSUE THREAD

**Issue by bammerlaan** [vmavromatis/Lemmy-keyboard-navigation#2]
Hey, thanks for creating this! Any chance you could add hjkl navigation as used in Vim? I got used to it with RES and I kind of miss it.

**Comment by vmavromatis** [comment]
Hey! Could you give [boobslider100's](https://lemmy.world/post/1003536) original script a go and see if it suits you maybe? If not let me and we can try to put it together here, I'm actively maintaining this - just if so let me know which keys you would use.

**Comment by bammerlaan** [comment]
Ah good stuff! Yes, the original script works great with hjkl navigation, but a and z for up- and downvoting doesn't work with it, unfortunately. 

Well, if you could duplicate the arrow keys' behavior with hjkl that would be the easiest, I suppose. [Here's what keys use what arrows](https://catonmat.net/images/why-vim-uses-hjkl/adm-3a-hjkl-keyboard.jpg) Would be great, but don't sweat it!

**Comment by vmavromatis** [comment]
I merged @aglidden 's PR, this should be good now 🎉   Please test, and let me know if all OK.

**Comment by bammerlaan** [comment]
Seems to work great, thanks for incorporating it!

**Comment by zurvan2** [comment]
First, this is awesome and I appreciate it. 

It would also be really nice if the vi-keys *replaced* the arrow keys (maybe optionally?), so the arrow keys could still be used by the browser to scroll the page around normally.

**Comment by vmavromatis** [comment]
> First, this is awesome and I appreciate it. 
> 
> 
> 
> It would also be really nice if the vi-keys *replaced* the arrow keys (maybe optionally?), so the arrow keys could still be used by the browser to scroll the page around normally. 

Yeah I have some ideas about giving the user the option to choose and also bundling it as a browser extension to make it more user friendly. For the time being you could try to use the hjkl fork https://github.com/InfinibyteF4/Lemmy-HJKL-keyboard-navigation see if it suits your needs

**Comment by zurvan2** [comment]
That looks promising, but I can't seem to get it to run in TamperMonkey. It doesn't seem to have the greasyfork location either. (and seems to have issues turned off in github? or maybe they just don't appear on forks)

**Comment by vmavromatis** [comment]
Hmmm no idea what is going on there, but from the looks of it he's missing a @match from his headers, maybe try adding that on top of the script?

`// @match         https://*/*`

Apart from that you should be able to c/p [this](https://raw.githubusercontent.com/InfinibyteF4/Lemmy-HJKL-keyboard-navigation/main/lemmy-keyboard-navigation.js) into Tampermonkey.

In any case, I will have time to work on this Switch improvement later this week.

**Comment by aglidden** [comment]
I made a PR to add a toggle for "vim on, arrows off" or "vim off, arrows on": https://github.com/vmavromatis/Lemmy-keyboard-navigation/pull/5
