### ISSUE TITLE
Release on Firefox Add-ons

### ISSUE THREAD

**Issue by GeckoEidechse** [vmavromatis/Lemmy-keyboard-navigation#26]
Next to being on the Chrome Extension store, it would be very much appreciated if this extension was also released for Firefox via [addons.mozilla.org](https://addons.mozilla.org/firefox/).

Supposedly there's little to none changes that need to be made to make it compatible with Firefox: https://extensionworkshop.com/documentation/develop/porting-a-google-chrome-extension/

After that you should be able to [publish the extension for Firefox](https://extensionworkshop.com/documentation/publish/).

**Comment by vmavromatis** [comment]
Submitted and awaiting review :)

Actually I just discovered a FF bug....  MutationObserver is very flaky on FF...... works fine on Chrome. I opened #29 bug

**Comment by vmavromatis** [comment]
Approved by mozilla -> https://addons.mozilla.org/en-US/firefox/addon/lemmy-keyboard-navigation/

Looks like they approved the first xpi I filed before the bugfix. Which means there is a bug on lemmy-ui, workaround is make 1 comment click, then script loads and runs forever. Hopefully they will soon approve my updated xpi.
