### ISSUE TITLE
Clicking "Next" or "Prev" does not move the selector to the first article of the page

### ISSUE THREAD

**Issue by n2burns** [vmavromatis/Lemmy-keyboard-navigation#32]
When you use the keyboard shortcuts "L" or "H" on the main page, the cursor resets to the top of the new page, as expected. If you instead click the "Next" or "Prev" button at the bottom of the page, it stays at the same number of articles down you were on the old page.

**Comment by vmavromatis** [comment]
Admittedly the workflow of using BOTH keyboard and mouse is bit weird :P however [this](https://github.com/vmavromatis/Lemmy-keyboard-navigation/pull/33) should do the trick 😃
