### ISSUE TITLE
Light Mode Support

### ISSUE THREAD

**Issue by Tamnac** [vmavromatis/Lemmy-keyboard-navigation#49]
Currently the extensions seems to be focused on dark mode, resulting in very weird and impossible to read looks when using a light theme.

You *can* change the background color in settings, however manually changing that twice a day is bothersome, and that still leaves broken, illegible text.

Examples:

Light mode with dark background
<img width="801" alt="image" src="https://github.com/vmavromatis/Lemmy-keyboard-navigation/assets/49466795/059b5405-3133-45f8-99fa-fb8db35cf5a9">

Light mode with light background
<img width="765" alt="image" src="https://github.com/vmavromatis/Lemmy-keyboard-navigation/assets/49466795/7c66ed1c-34f6-4257-921c-a8aa01b930b6">

**Comment by heavyboots** [comment]
For anyone changing this color a lot, I find "Navajo White" aka #FFDEAD to be both quite usable and memorable.

**Comment by vmavromatis** [comment]
Actually something weird on **my setup** (I doubt anyone else is using this)...  I have this flag on `chrome://flags/#enable-force-dark` always. So using #FFDEAD this is what I see:

<img width="1279" alt="image" src="https://github.com/vmavromatis/Lemmy-keyboard-navigation/assets/8668731/c5da824a-efeb-4ba7-a061-151f664185ee">

need to find a color which is usable for both light/dark theme and ideally also working for users with the chrome dark flag on... If no solution is found, I will stop using the flag and sacrifice myself for the greater good 🤷

**Comment by heavyboots** [comment]
Yeah it definitely works better on light themes. I think the only way we're ever going to see this work correctly is by having a separate default for light and dark themes. Since Lemmy can apparently detect what your browser is using and match it, I would think there must be some way to get that info and pick a selection color based on it. 🤔

**Comment by vmavromatis** [comment]
maybe with [this](https://stackoverflow.com/a/76675307/8357094)

**Comment by vmavromatis** [comment]
I found a way to set the color based on theme selection, but seems it keeps getting overriden by localStorage

```
//Default bg color based on theme selection
if(document.getElementById("app").getAttribute("data-bs-theme")==="light"){
    var defaultTheme = "#FFDEAD"
  } else {
    defaultTheme = "#373737"
}
```

Maybe @InfinibyteF4 can do his magic ✨ 

Edit: fixed and opened a PR. @heavyboots if you wanna test try [that](https://github.com/vmavromatis/Lemmy-keyboard-navigation/blob/Automatically-set-dark/light-defaults/lemmy-keyboard-navigation.user.js) with Tampermonkey or sth. Leaving the color field empty sets a default color which differs between dark/light.
