### ISSUE TITLE
Reply does not work

### ISSUE THREAD

**Issue by Atemu** [vmavromatis/Lemmy-keyboard-navigation#51]
Navigating to a post and hitting reply does not focus the text editor as expected.

Hitting `r` on a comment shows its source instead.

(Using Firefox to browse lemmy.ml)

**Comment by vmavromatis** [comment]
Just to clarify
'R' on a post takes you to the respective community
'R' on a comment opens the reply box

Can't reproduce though... can you clarify what's a 'source'? is it parent comment? Stupid Q but are you sure you're logged in?

**Comment by Atemu** [comment]
1. I open a post in a new tab
2. Navigate back up to the post because the first comment is selected for some reason?
3. Hit `r` to reply to the post
4. Nothing happens

Source is the comment's source markup in raw form. Reddit had a button named "source" for this and Lemmy has an equivalent button with just an icon.

**Comment by vmavromatis** [comment]
Yeah, looks like version 19 broke something there (lemmy.ml uses 19 unlike lemmy.world which is still on 18). The PR #53 does fix the issue, however it creates some other ones, will keep you posted.
