### ISSUE TITLE
Inbox button does not work

### ISSUE THREAD

**Issue by Atemu** [vmavromatis/Lemmy-keyboard-navigation#52]
Hitting `i` on any page does not open the inbox on Firefox browsing lemmy.ml.

**Comment by vmavromatis** [comment]
Hmmmm "i" is not implemented AFAIK.. we can add it

**Comment by InfinibyteF4** [comment]
Did you press your dialog key (set to `G` by default) before pressing `I`?

**Comment by Atemu** [comment]
Ah, I was not aware that I had to.
