### ISSUE TITLE
New mlmym image viewer breaks "next post" functionality

### ISSUE THREAD

**Issue by nicolairathjen** [vmavromatis/Lemmy-keyboard-navigation#54]
(Tested on old.lemmy.world who uses mlmym 0.0.37)

When the selected post has an expanded image, it is not possible to select the next post, and the selected post will keep being selected.

*Steps to reproduce:*
1. Go to an mlmym front page or community page
2. Expand image
3. Press "J" (or go to "next post" by other means)

Actual result: Selected post keeps being selected.
Expected result: Next post should be selected, and the current post should be unselected.

**Comment by shadshack** [comment]
I can confirm this behavior. Additionally, the console throws an error:
`Uncaught TypeError: imgContainer.querySelector(...) is null`

This only happens for image posts. Text posts or link-only posts there is no console error and it behaves as intended.

Looks like changing line 1463 to the following (adding the `.open`) makes it work as intended, although there is still the console error.
`    const imgContainer = currentEntry.querySelector(".expando.open>.image");`
