### ISSUE TITLE
Update to work with old.lemmy codebase

### ISSUE THREAD

**Issue by dochdoch** [vmavromatis/Lemmy-keyboard-navigation#9]
Lemmy.world has implemented https://old.lemmy.world 
Your keyboard navigation code is great. I appreciate it greatly. Any chance you can get it to work with the modified front end? The code base is here:

https://github.com/rystaf/mlmym

**Comment by vmavromatis** [comment]
I will take a look into it! I love mlmym. Shouldn't be too hard to port it there.

Currently working on packaging it as chrome extension, will look at it after that.

**Comment by vmavromatis** [comment]
fyi @aglidden  - I started a [branch](https://github.com/vmavromatis/Lemmy-keyboard-navigation/tree/add-mlmym-support) to work on this. Just site detection & JK navigation works now. Ideally need to set DOM selectors as variables to change when isOldLemmy true. Contributions welcome!

**Comment by aglidden** [comment]
@vmavromatis To get other languages (#10) working we have to change many of the DOM selectors anyways, so we can kill two birds with one stone there. Unfortunately the DOM for some elements such as comment bottom buttons (comment-bottom-btns) isn't unique per button except for the text inside them which changes when you change language. I really wish lemmy was better with element ids... We'll have to do something like currentItem.querySelectorAll(".comment-bottom-btns>button")[2] for "reply" and hope the buttons are always in the same order on all servers.

**Comment by vmavromatis** [comment]
@dochdoch the script is finally [here](https://github.com/vmavromatis/Lemmy-keyboard-navigation/raw/add-mlmym-support/lemmy-keyboard-navigation.user.js) 

Feel free to test and provide feedback. ALL credits go to @InfinibyteF4 🏆 

Ideally I would like both scripts running at once with some site detection. I am looking into the @require functionality so we can have the code be more modular too https://wiki.greasespot.net/Metadata_Block#@require
sth like
- main js defines which code to run and sets global stuff like settings/variables
- newlemmy js has its  init and its own functions
- oldlemmy js has its init and its own functions
